CFLAGS = -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)

testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out

cardtest1: cardtest1.c dominion.o rngs.o
	gcc -o cardtest1 -g cardtest1.c dominion.o rngs.o $(CFLAGS)

cardtest2: cardtest2.c dominion.o rngs.o
	gcc -o cardtest2 -g cardtest2.c dominion.o rngs.o $(CFLAGS)

cardtest3: cardtest3.c dominion.o rngs.o
	gcc -o cardtest3 -g cardtest3.c dominion.o rngs.o $(CFLAGS)

cardtest4: cardtest4.c dominion.o rngs.o
	gcc -o cardtest4 -g cardtest4.c dominion.o rngs.o $(CFLAGS)

unittest1: unittest1.c dominion.o rngs.o
	gcc -o unittest1 -g unittest1.c dominion.o rngs.o $(CFLAGS)

unittest2: unittest2.c dominion.o rngs.o
	gcc -o unittest2 -g unittest2.c dominion.o rngs.o $(CFLAGS)

unittest3: unittest3.c dominion.o rngs.o
	gcc -o unittest3 -g unittest3.c dominion.o rngs.o $(CFLAGS)

unittest4: unittest4.c dominion.o rngs.o
	gcc -o unittest4 -g unittest4.c dominion.o rngs.o $(CFLAGS)

randomtestcard1: randomtestcard1.c dominion.o rngs.o
	gcc -o randomtestcard1 -g randomtestcard1.c dominion.o rngs.o $(CFLAGS)
	
randomtestcard2: randomtestcard2.c dominion.o rngs.o
	gcc -o randomtestcard2 -g randomtestcard2.c dominion.o rngs.o $(CFLAGS)
	
randomtestadventurer: randomtestadventurer.c dominion.o rngs.o
	gcc -o randomtestadventurer -g randomtestadventurer.c dominion.o rngs.o $(CFLAGS)
	
player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

all: playdom player testDrawCard testBuyCard badTestDrawCard randomtestcard1 randomtestcard2 randomtestadventurer

randomtestcard1.out: randomtestcard1.c dominion.c rngs.c
	echo "Dominion Random Test: Card 1" > randomtestcard1.out
	gcc -o randomtestcard1 dominion.c rngs.c randomtestcard1.c $(CFLAGS)
	randomtestcard1 >> randomtestcard1.out
	echo "------- Card 1 GCOV info --------" >> randomtestcard1.out
	gcov -b -f dominion.c >> randomtestcard1.out 
	
randomtestcard2.out: randomtestcard2.c dominion.c rngs.c 
	echo "Dominion Random Test: Card 2" > randomtestcard2.out 
	gcc -o randomtestcard2 dominion.c rngs.c randomtestcard2.c $(CFLAGS)
	randomtestcard2 >> randomtestcard2.out
	echo "------- Card 2 GCOV info -------" >> randomtestcard2.out 
	gcov -b -f dominion.c >> randomtestcard2.out

randomtestadventurer.out: randomtestadventurer.c dominion.c rngs.c 
	echo "Dominion Random Test: Adventurer" > randomtestadventurer.out 
	gcc -o randomtestadventurer dominion.c rngs.c randomtestadventurer.c $(CFLAGS)
	randomtestadventurer >> randomtestadventurer.out
	echo "------- Adventurer GCOV info -------" >> randomtestadventurer.out
	gcov -b -f dominion.c >> randomtestadventurer.out 

unittestresults.out: cardtest2.c cardtest3.c cardtest4.c unittest1.c unittest2.c unittest3.c unittest4.c dominion.c rngs.c
	echo "Dominion Unit Tests:" > unittestresults.out
	echo "See write-up for why card test 1 does not appear here." >> unittestresults.out
	echo "Card test 2:" >> unittestresults.out
	gcc -o cardtest2 dominion.c rngs.c cardtest2.c $(CFLAGS)
	cardtest2 >> unittestresults.out
	echo "------- Card test 2 GCOV info --------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	echo "Card test 3:" >> unittestresults.out
	gcc -o cardtest3 dominion.c rngs.c cardtest3.c $(CFLAGS)
	cardtest3 >> unittestresults.out
	echo "------- Card test 3 GCOV info -------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	echo "Card test 4:" >> unittestresults.out
	gcc -o cardtest4 dominion.c rngs.c cardtest4.c $(CFLAGS)
	cardtest4 >> unittestresults.out
	echo "------- Card test 4 GCOV info -------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	echo "Function test 1:" >> unittestresults.out
	gcc -o unittest1 dominion.c rngs.c unittest1.c $(CFLAGS)
	unittest1 >> unittestresults.out
	echo "------- Unit test 1 GCOV info -------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	echo "Function test 2:" >> unittestresults.out
	gcc -o unittest2 dominion.c rngs.c unittest2.c $(CFLAGS)
	unittest2 >> unittestresults.out
	echo "-------- Unit test 2 GCOV info ------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	echo "Function test 3:" >> unittestresults.out
	gcc -o unittest3 dominion.c rngs.c unittest3.c $(CFLAGS)
	unittest3 >> unittestresults.out
	echo "------- Unit test 3 GCOV info ------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	echo "Function test 4:" >> unittestresults.out
	gcc -o unittest4 dominion.c rngs.c unittest4.c $(CFLAGS)
	unittest4 >> unittestresults.out
	echo "------ Unit test 4 GCOV info -------" >> unittestresults.out
	gcov -b -f dominion.c >> unittestresults.out
	

clean:
	rm -f *.o playdom.exe playdom test.exe test player player.exe randomtestadventurer randomtestcard1 randomtestcard2 testInit testInit.exe *.gcov *.gcda *.gcno *.so
